# -*- coding: utf-8 -*-
"""TangoFlux_Pretrained.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uodtQGo78gnkQPsROgbeMi28zPRqcmjY
"""

from .model_interface import ModelInterface
from tangoflux import TangoFluxInference
from pathlib import Path

class TangoFluxModel(ModelInterface):
    STEPS = 50
    DURATION = 4
    
    def __init__(self):
        super().__init__()
    
    def load(self, path: str = ""):
        if self.model != None:
            print("Error: Model already loaded")
            return
        
        # Use Pre-Trained model
        if path == "" or not Path(path).exists():
            print("Checkpoint file not found, loading pre-trained model...")
            self.model = TangoFluxInference(name='declare-lab/TangoFlux')
        else:
            try:
                pass
                # TODO: load custom tangoflux
                #self.model = build_model(ckpt_path=path, model_name="audioldm-s-text-ft")
            except:
                raise ValueError("Incorrect checkpoint path to load AudioLDM model.")  
        
        
    def save(self, path: str = ""):
        
        if path == "":
            print("Error: A save path was not specified!")
            
        try:
            pass
        except:
            pass

    def train(self):
        pass

    def infer(self, prompt: str, duration: float):
        audio = None
        
        if self.model == None:
            print("Error: Model not loaded")
            return audio
            
        audio = self.model.generate(prompt, steps=self.STEPS, duration=self.DURATION)
        
        return audio

